"""Initial migration

Revision ID: 09ff8ad0a441
Revises: 
Create Date: 2025-06-22 15:05:43.255881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ff8ad0a441'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('featured_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_posts_featured_order'), 'posts', ['featured_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_featured_order'), table_name='posts')
    op.drop_column('posts', 'featured_order')
    # ### end Alembic commands ###
