"""add icon to category

Revision ID: bc3932df357b
Revises: 1e2e58fa2cbd
Create Date: 2025-06-22 15:24:03.938190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3932df357b'
down_revision: Union[str, Sequence[str], None] = '1e2e58fa2cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.String(), nullable=True))
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###
